FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json ./

# Install all dependencies including devDependencies
RUN npm install

# Copy all application files
COPY . .

EXPOSE 3000

CMD ["npm", "watch"]