version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DEBUG=True  # Setting DEBUG to True for development
    env_file:
      - .env
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
      - "5678:5678"
    command: poetry run python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev.react
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"  # Maps React default port
    stdin_open: true
    tty: true

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: basicapp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend

volumes:
  pgdata: