FROM pytorch/pytorch:2.6.0-cuda12.4-cudnn9-runtime

WORKDIR /app

# Copy only necessary configuration files to leverage Docker cache
COPY pyproject.toml poetry.lock ./

# Install Poetry and dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc libc-dev \
    && pip install poetry \
    && pip install debugpy \
    && poetry config virtualenvs.create false \
    && poetry install --no-root \
    && apt-get remove -y gcc libc-dev \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY . /app

RUN pip install poetry

CMD ["poetry", "run", "uvicorn", "aimodel:app", "--host", "0.0.0.0", "--port", "8000"]